version: '3'
services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - '.:/bot'
    working_dir: /bot
    command: 'python launcher.py'
    environment:
      PORT: 8008
    ports:
      - '8008:8008'
